# Generated by Django 4.1.3 on 2022-11-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immigration_forum', '0002_alter_country_options_country_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='snippet',
            field=models.CharField(default='This is a snippet info about the country!', max_length=255),
        ),
    ]
