# Generated by Django 4.1.3 on 2022-11-23 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('immigration_forum', '0003_country_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='immigration_forum.country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='snippet',
            field=models.CharField(max_length=255),
        ),
    ]
