# Generated by Django 4.1.3 on 2022-11-28 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('immigration_forum', '0004_post_country_alter_country_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immigration_forum.country'),
        ),
    ]
