# Generated by Django 4.1.3 on 2022-11-28 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('immigration_forum', '0005_alter_post_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='immigration_forum.country'),
        ),
    ]
