# Generated by Django 4.1.3 on 2022-12-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immigration_forum', '0008_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantprofile',
            name='bio',
            field=models.TextField(max_length=1200),
        ),
    ]
